### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by anonymous992** [ThePieMonster/HideMockLocation#21]
When I try to install the apk, it fails with "app not installed" on my oneplus 6 with carbonrom (android 11). I tried installing it on my nexus 6p with stock rom (android 8) too. There it fails with "parse error".

**Comment by ThePieMonster** [comment]
@anonymous992 Thanks for the report, this is a known bug however a fix is in the works currently. 
I would also like to get a idea of what individuals are using the app for. If you wouldn't mind posting your info on the "issue" thread that is next to yours that would be great!
